# This is a Docker Compose file for setting up Loki and Promtail for log aggregation and monitoring.
# It uses the Grafana Loki and Promtail images and configures them to work together.
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ../logs:/app/logs  # ✅ Use the logs folder
      - ./promtail-config.yaml:/etc/promtail/config.yaml
    command: -config.file=/etc/promtail/config.yaml
    restart: unless-stopped
