global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'playwright-metrics'
    static_configs:
      - targets: ['host.docker.internal:9100'] # or 'metrics-server:9100' if using Docker-internal network
