scrape_configs:
  - job_name: playwright-logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: playwright
          __path__: /report/logs/*.jsonl

    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            event: event
            suite: suite
            title: title
            tags: tags
            status: status
            error: error
            duration: duration
            project: project
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          event:
          suite:
          status:
          project:
